version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    expose:
      - "5000"
    restart: always

  web:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
